stages:
  mystage:
    cmd: python train.py --epochs 10 --batch 32
    deps:
    - train.py
    - data
   
    metrics:
    - metrics.txt:
        cache: false
    plots:
    - classes.csv:
        cache: false
    - logs.csv:
        cache: false
