name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: [self-hosted]
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
        with:
          sudo: false
          
      - name: Train model
        
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies
          #dvc pull data --run-cache        # Pull data & run-cache from S3
          dvc repro                        # Reproduce pipeline
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" >> report.md
          git fetch --prune  --unshallow
          dvc metrics diff main --show-md >> report.md
          
          # Publish confusion matrix diff
          echo "## Plots" >> report.md
          echo "### Class confusions" >> report.md
          dvc plots diff --target classes.csv --template confusion -x actual -y predicted --show-vega main > vega.json
          vl2png vega.json -s 1.5 > confusion_plot.png
          echo "![](./confusion_plot.png)" >> report.md

          # Publish regularization function diff
          echo "### test accuracy " >> report.md
          dvc plots diff --target logs.csv -x test_accuracy --show-vega main > vega.json
          vl2png vega.json -s 1.5 > plot.png
          echo "![](./plot.png)" >> report.md
          
          
          
          cml comment create --target=pr --publish report.md

