name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: [self-hosted]
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Train model
        
        run: |
          pip install -r requirements.txt  # Install dependencies
          #dvc pull data --run-cache        # Pull data & run-cache from S3
          dvc repro                        # Reproduce pipeline
      - name: Create CML report
        
        run: |
          # Compare metrics to main
          git fetch --depth=1 origin main:main 
          dvc metrics diff --show-md main >> report.md
          
          
          # Plot training loss function diff
          dvc plots diff  --target logs.csv --show-vega main > vega.json
          vl2png vega.json > plot.png
          echo '![](./plot.png "Test Loss")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
